import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from deeptrader_data_common import process_stocks_data

# Hardcoded DJIA stocks list (學姐的版本)
# Note: Removed CRM (listed 2004-06-23) and V (listed 2008-03-19) to match feature34-Inter (28 stocks)
# DJIA_STOCKS = [
#     "AAPL", "AMGN", "AXP", "BA", "CAT", "CSCO", "CVX", "DIS", "GS",
#     "HD", "HON", "HPQ", "IBM", "INTC", "JNJ", "JPM", "KO", "MCD", "MMM",
#     "MRK", "MSFT", "NKE", "PFE", "PG", "TRV", "UNH", "VZ", "WBA"
# ]

# 2024-11-02 updated DJIA stocks list
DJIA_STOCKS = [
    "UNH",   # UnitedHealth Group
    "GS",    # Goldman Sachs
    "MSFT",  # Microsoft
    "HD",    # The Home Depot
    "CAT",   # Caterpillar
    "AMGN",  # Amgen
    "MCD",   # McDonald's
    "CRM",   # Salesforce.com
    "V",     # Visa
    "AXP",   # American Express
    "TRV",   # Travelers
    "AAPL",  # Apple
    "JPM",   # JPMorgan Chase
    "IBM",   # IBM
    "HON",   # Honeywell International
    "AMZN",  # Amazon
    "PG",    # Procter & Gamble
    "JNJ",   # Johnson & Johnson
    "BA",    # Boeing
    "CVX",   # Chevron
    "MMM",   # 3M
    "MRK",   # Merck Sharp & Dohme
    "DIS",   # Walt Disney
    "WMT",   # Walmart Inc
    "NKE",   # Nike
    "KO",    # Coca-Cola
    "CSCO",  # Cisco Systems
    "VZ",    # Verizon
    "INTC",  # Intel
]

if __name__ == '__main__':
    # Choose feature mode:
    # - 'basic': OHLCV (5 features)
    # - 'basic_sentiment': OHLCV + Sentiment (6 features)
    # - 'full': all features (34 features)
    FEATURE_MODE = 'basic'

    # Trading dates from DIA ETF CSV (generated by market_data/deeptrader_market.py)
    # Run deeptrader_market.py first to generate DIA.csv
    TRADING_DATES_CSV = './market_data/DIA.csv'

    # Sentiment file (required for basic_sentiment mode)
    # Run generate_sentiment.py first to create this file
    PRECOMPUTED_SENTIMENT_FILE = './sentiment_scores.npy'

    # Process DJIA stocks
    # Note: Using adjusted OHLC (還原開高低收) - calculated in deeptrader_data_common.py
    # Yahoo Finance provides Adj Close, and we calculate adjustment ratio to apply to O/H/L
    unique_stock_ids, reshaped_data = process_stocks_data(
        stock_list=DJIA_STOCKS,
        start_date='2013-01-01',       # Final data range start
        end_date='2026-02-28',         # Final data range end
        feature_mode=FEATURE_MODE,     # Automatically determines feature count
        output_prefix='./',
        download_start_date='2010-01-01',  # Download more data for technical indicators
        download_end_date='2026-03-01',    # yfinance end_date is exclusive
        trading_date_reference='DIA',      # Use DIA (Dow Jones ETF) for trading days
        trading_dates_csv=TRADING_DATES_CSV,
        precomputed_sentiment_file=PRECOMPUTED_SENTIMENT_FILE if FEATURE_MODE == 'basic_sentiment' else None
    )